### ISSUE TITLE
go-unarr produces corrupt files

### ISSUE THREAD

**Issue by bhechinger** [gen2brain/go-unarr#1]
```
wonko@deepthought:~/unarr$ ls -l
total 2595896
-rw-r--r-- 1 wonko wonko 2658193139 Sep 17 22:30 unarr-Corrupt_file.mkv
-rw-r--r-- 1 wonko wonko 2658193139 Sep 18 10:22 unrar-e-Working_file.mkv
wonko@deepthought:~/unarr$ md5sum *
8f739c886345d1ab0e90e1c784270bac  unarr-Corrupt_file.mkv
4109ac34d20fe03494e12cdce24f270b  unrar-e-Working_file.mkv
wonko@deepthought:~/unarr$
```

From here: https://github.com/bhechinger/tv/blob/master/donescript/main.go#L63

The version of go-unarr I have is: 6fec55926dd18e1b15210a3a68456452b7b50f43

go 1.8.3 on Ubuntu 17.04

**Comment by gen2brain** [comment]
That happens with every file or specific one? Can you share a link maybe where I can download file to test?

**Comment by bhechinger** [comment]
Seems to be happening every time. Let me find somewhere to stash one of these for you. They tend to be large.

**Comment by gen2brain** [comment]
unarr library doesn't work with rar files that are split across multiple files.

**Comment by bhechinger** [comment]
so when you say unarr library you mean https://github.com/sumatrapdfreader/sumatrapdf/tree/master/ext/unarr, right?

**Comment by gen2brain** [comment]
right, these are bindings for that library, bundled.

**Comment by bhechinger** [comment]
Ok, so I'll go bother them about that then.

Thanks!
