### ISSUE TITLE
Add Go Modules compatible tag

### ISSUE THREAD

**Issue by elioengcomp** [gen2brain/go-unarr#17]
I see this repo has tag `0.1.0`. However, that tag is not following Go Modules semantic versioning rules, since it is missing the `v` prefix. The Go Modules compatible version should look like `v0.1.0` ([Source](https://blog.golang.org/publishing-go-modules)). Without that, users need to rely on commit hashes pseudo-versions to resolve this module.

Can you please add a Go Modules compatible version so we can resolve actual release tags instead of commit hashes pseudo versions?

**Comment by elioengcomp** [comment]
Also, because the tag is not compatible, in GoCenter we can only see pseudo-versions, even though there is a tagged release.

https://search.gocenter.io/github.com/gen2brain/go-unarr?tab=versions

**Comment by gen2brain** [comment]
Sure, I updated the release version and released a new patch version.

**Comment by elioengcomp** [comment]
Thanks!
