### ISSUE TITLE
Can not support COPY mode from 7z

### ISSUE THREAD

**Issue by jiongshushu** [gen2brain/go-unarr#20]
Hi, i try to get sub file name from 7z file, which compress by "7z a -m=0". and it get the wrong filename

![image](https://user-images.githubusercontent.com/37547536/122159107-5e78db00-cea0-11eb-8b92-da95e28ebda0.png)

**Comment by gen2brain** [comment]
C sources are updated, and there is now a new function `RawName()` beside `Name()`, so you might want to check again.
