### ISSUE TITLE
untar error

### ISSUE THREAD

**Issue by wujianqiangwjq** [gen2brain/go-unarr#29]
error:  ! tar.c:54: Unknown entry type '2', but the tar -xf  c.tar  is ok.

**Comment by gen2brain** [comment]
@wujianqiangwjq can you create the simple .tar file that can be used to reproduce the error? Such issues are better to be reported "upstream" https://github.com/selmf/unarr.

**Comment by CRThaze** [comment]
For those curious, this error happens when the archive has Symlinks. Which the unarr library does not support.

**Comment by gen2brain** [comment]
Thanks @CRThaze , I guess this can be closed then.
