### ISSUE TITLE
When un7zip size of 100GB report an error ：'unarr: No valid RAR, ZIP, 7Z or TAR archive'

### ISSUE THREAD

**Issue by haoyutc** [gen2brain/go-unarr#32]
Use dd create 1GB 10GB 100GB file 
dd if=/dev/random of=data1GB.bin bs=40m count=25 
dd if=/dev/random of=data10GB.bin bs=400m count=25 
dd if=/dev/random of=data100GB.bin bs=4000m count=25 
and use command '7z a'  archive to data1GB.7z  data10GB.7z  data100GB.7z
When un7zip size of 100GB.7z and 10GB.7z files report an error ：'unarr: No valid RAR, ZIP, 7Z or TAR archive'
But, un7zip size under 1GB file successfully!!!

Last，I test 2GB / 3GB / 4GB /5GB ,only 2GB  file success, and above 2GB file failed!

OS : macOS 12.4
GOVERSION="go1.18.3"

**Comment by gen2brain** [comment]
These are only bindings, I believe there is already a similar open issue at unarr. I am closing this as it will not be fixed here, direct your issues to upstream.

**Comment by gen2brain** [comment]
This should be fixed, thanks for reporting, and sorry for closing too early.

**Comment by sayconect** [comment]
@gen2brain , still have this issue.

**Comment by gen2brain** [comment]
As written above, the change will not happen here so there is no point opening issues here.
