### ISSUE TITLE
function without prototype warnings

### ISSUE THREAD

**Issue by mbetel** [gen2brain/go-unarr#38]
When compiling with newest apple clang (14.0.3) I now get the warning : 
`warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]`
 on zlib/adler32.c, zlib/crc32.c, zlib/inffast.c, zlib/inflate.c, zlib/inftrees.c, zlib/zutil.c.

My guess is the embedded zlib will need .h files in the near future? , but I am no C expert...

**Comment by gen2brain** [comment]
It is just a warning, you can ignore it, or configure CFLAGS with something like `-Wno-deprecated-non-prototype`. I guess that `-std=c99` should be used/defined somewhere instead, C2x, as I understand, would become `c23`. Not all projects will magically support `c23` overnight.

**Comment by gen2brain** [comment]
And I see that there is already `-std=gnu99`, I guess clang doesn't support that, can you check?

**Comment by gen2brain** [comment]
Changed to c99 in https://github.com/gen2brain/go-unarr/commit/4d5d46ad7d402fd51f4aff29381944a18e9ef6b4, can you check with the latest code?

**Comment by jamelt** [comment]
I just tried this out and it doesn't fix it.

**Comment by jamelt** [comment]
@gen2brain We might need to back that change out. Apparently, it works fine on M1/2 Macs, but it can cause build errors on the x86 Macs.

**Comment by gen2brain** [comment]
These were just warnings, not build errors. So now it warns that such suppression options do not exist. I do not see how that is related to M1/2 (i.e. architecture), it should be associated with the Clang version, no?

**Comment by jamelt** [comment]
You're right, the issue at hand is linked to the Clang version. To address this in my team project, I created a script in the Makefile that checks if the flags are supported before exporting them. However, I'm unsure if the same can be done for the cgo flags within the package.

``` makefile
CLANG_EXISTS := $(shell command -v clang 2> /dev/null)
FLAG_SUPPORTED := $(shell echo 'int main(){}' | clang -x c - -o /dev/null -Wno-typedef-redefinition -Wno-deprecated-non-prototype 2>&1 && echo YES)

ifdef CLANG_EXISTS
ifeq ($(FLAG_SUPPORTED),YES)
export CGO_CFLAGS := -Wno-typedef-redefinition -Wno-deprecated-non-prototype
endif
endif

all:
@echo $(CGO_CFLAGS)
``` 

I was concerned about the potential negative impact this could have on people currently.

**Comment by gen2brain** [comment]
Something like this should be possible, with predefined macros, if you can tell me the exact major versions that need to be checked.
```
#if defined(__clang__) && __clang_major__ >= 16
#cgo CFLAGS: -Wno-typedef-redefinition -Wno-deprecated-non-prototype
#endif

```

**Comment by gen2brain** [comment]
This should be fixed now, with the Zlib update.
