### ISSUE TITLE
no entries in 7z archive

### ISSUE THREAD

**Issue by kaxap** [gen2brain/go-unarr#4]
Go version: 1.11
Platform: Windows 10

go-unarr installed with the following command:
```
go get github.com/gen2brain/go-unarr
```

Trying to extract data from a .7z archive. 
The archive contains exactly one file. However, go-unarr can't find any entries, e.g. `a.List()` returns an empty slice and `a.Entry()` returns `io.EOF`

My code:

```go
package main

import (
    "github.com/gen2brain/go-unarr"
    "fmt"
    "io"
)

func main() {
	a, err := unarr.NewArchive("something.7z")
	if err != nil {
		panic(err)
	}

	defer a.Close()

	err = a.Entry()
	if err != nil {
		panic(err)
	}

	list, err := a.List()
	if err != nil {
		panic(err)
	}
	fmt.Println(list)

	err = a.Entry()
	if err != nil {
		if err == io.EOF {
			fmt.Println("No files found")
			return
		}
		panic(err)
	}

	data, err := a.ReadAll()
	fmt.Println(len(data))
}
```

This prints
```
[]
No files found
```

But should print
```
[something.txt]
16
```

Base64 encoded contents of `something.7z`:

```
N3q8ryccAASTCs7jFAAAAAAAAABiAAAAAAAAAF5649QBAA/vu79oZWxsbywgd29ybGQhAAEEBgABCRQABwsBAAEhIQEADBAACAoBuW/kcgAABQEZDAAAAAAAAAAAAAAAABEdAHMAbwBtAGUAdABoAGkAbgBnAC4AdAB4AHQAAAAUCgEAL22u3BFM1AEVBgEAIAAAAAAA
```

**Comment by kaxap** [comment]
Ubuntu 16.04 LTS/Go 1.11 - same issue

**Comment by gen2brain** [comment]
Just tried with your file and I can reproduce it. How is that archive created, anything special? There is also test.7z archive in testdata, also single .txt file in it, and it works with it.

**Comment by gen2brain** [comment]
Hmm, it seems your file starts with BOM https://en.wikipedia.org/wiki/Byte_order_mark , can you try to remove it and packa again etc.

**Comment by kaxap** [comment]
I have created it using conventional desktop 7zip binary from Sourceforge for Windows

**Comment by gen2brain** [comment]
This is fixed in https://github.com/gen2brain/go-unarr/commit/b170f54f13fe75763a8e28c0e6cbbf6611ef87bd
