### ISSUE TITLE
genuine question regarding cap vs. len

### ISSUE THREAD

**Issue by sug0** [gen2brain/go-unarr#6]
https://github.com/gen2brain/go-unarr/blob/master/unarr.go#L50

In this line, you're using `cap` over `len`, which seems wrong to me. Assuming you pass a smaller slice `s` with `len(s) < cap(s)`, and an archive is only valid within the range of the new slice, isn't this going to cause problems?

**Comment by gen2brain** [comment]
Yes, you were right, fixed now. Sorry, missed paying attention to this issue.
